# Generated by Django 6.0.8 on 2026-09-23 16:11

import game.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('local', 'Same screen (hot seat)'), ('online', 'Two browsers (share a link)')], default='local', max_length=10)),
                ('white_key', models.CharField(default=game.models.new_key, max_length=32)),
                ('black_key', models.CharField(default=game.models.new_key, max_length=32)),
                ('state', models.JSONField()),
                ('version', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
