# Generated by Django 6.0.8 on 2026-09-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='ai_level',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Beginner'), (2, 'Easy'), (3, 'Medium'), (4, 'Hard')], null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='ai_side',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='game',
            name='mode',
            field=models.CharField(choices=[('ai', 'Against the computer'), ('local', 'Same screen (hot seat)'), ('online', 'Two browsers (share a link)')], default='local', max_length=10),
        ),
    ]
